version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DBPORT}'
    volumes:
      - data:/data/db
      - .:/usr/src/app
      - ./scripts/db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DBNAME}
volumes: 
  data: {}
